# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tablas201711' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tablas201711
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

end
